language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test -- --coverage
  - npm run build

branches:
  only:
    - master

notifications:
  email: true
